// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import HelloController from "./hello_controller"
import ResetFormController from "./reset_form_controller"
application.register("reset_form", ResetFormController)
application.register("hello", HelloController)
